// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhqcD8DyCa9pLy298fm96IsMzNWEDSxrk',
    appId: '1:437374817329:web:531cb26e690beaf2537110',
    messagingSenderId: '437374817329',
    projectId: 'directionsapp-baf3e',
    authDomain: 'directionsapp-baf3e.firebaseapp.com',
    storageBucket: 'directionsapp-baf3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyFIreOdtB1WaPyrgCycrQ4jDLvt8z-Fs',
    appId: '1:437374817329:android:f88feb2f3f80f82c537110',
    messagingSenderId: '437374817329',
    projectId: 'directionsapp-baf3e',
    storageBucket: 'directionsapp-baf3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHTgCJlIRTPrRmJpzQ5b5I1BXTcKHGRT8',
    appId: '1:437374817329:ios:1f90cb5b186d079f537110',
    messagingSenderId: '437374817329',
    projectId: 'directionsapp-baf3e',
    storageBucket: 'directionsapp-baf3e.appspot.com',
    iosClientId: '437374817329-tmra23n9aopqel5srkeindbm4fs6e288.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHTgCJlIRTPrRmJpzQ5b5I1BXTcKHGRT8',
    appId: '1:437374817329:ios:1f90cb5b186d079f537110',
    messagingSenderId: '437374817329',
    projectId: 'directionsapp-baf3e',
    storageBucket: 'directionsapp-baf3e.appspot.com',
    iosClientId: '437374817329-tmra23n9aopqel5srkeindbm4fs6e288.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebaFlutter',
  );
}
